apiVersion: v1
kind: Service
metadata:
  name: workflow-kubernetes-service
spec:
  selector:
    app: workflow-kubernetes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Esto depende de cómo quieras exponer el servicio
